name: Build Multi-Platform Executables

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for creating releases
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable_name: lms_helper_win64
            artifact_name: lms_helper_win64.exe
            icon_file: icons/logo.ico
          - os: macos-latest
            executable_name: lms_helper_macos
            artifact_name: lms_helper_macos
            icon_file: icons/logo.icns
          - os: ubuntu-latest
            executable_name: lms_helper_linux
            artifact_name: lms_helper_linux
            icon_file: icons/logo.icns

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv pip install -r requirements.txt
        uv pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --console --icon="${{ matrix.icon_file }}" scraper_public.py --clean --name="${{ matrix.executable_name }}"
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.executable_name }}
        path: |
          dist/${{ matrix.artifact_name }}
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/lms_helper_*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}